### ISSUE TITLE
retained value not incrementing

### ISSUE THREAD

**Issue by noobplayer48** [peturdainn/ESP32c3_deepsleep_wakestub_test#1]
hi, this is my esp monitor reading :

when i hard boot it using EN
      Build:Feb  7 2021
      rst:0x1 (POWERON),boot:0xc (SPI_FAST_FLASH_BOOT)
      SPIWP:0xee
      mode:DIO, clock div:1
      load:0x3fcd5810,len:0x438
      load:0x403cc710,len:0x918
      load:0x403ce710,len:0x25f4
      entry 0x403cc710
      E (71) esp_core_dump_flash: Incorrect size of core dump image: 81858548
      Deep sleep test: Booted, retained value 0, sleep in 2 seconds

After 10 seconds this is what i get :
      ESP-ROM:esp32c3-api1-20210207
      Build:Feb�ESP-ROM:esp32c3-api1-20210207
      Build:Feb�ESP-ROM:esp32c3-api1-20210207
      Build:Feb�ESP-ROM:esp32c3-api1-20210207
      Build:Feb�ESP-ROM:esp32c3-api1-20210207
      Build:Feb  7 2021

this is me pressing gpio 1 :
      rst:0x5 (DSLEEP),boot:0xc (SPI_FAST_FLASH_BOOT)
      ESP-ROM:esp32c3-api1-20210207
      Build:Feb  7 2021
      rst:0x5 (DSLEEP),boot:0xc (SPI_FAST_FLASH_BOOT)
After 10 sec :
      ESP-ROM:esp32c3-api1-20210207
      Build:Feb  7�ESP-ROM:esp32c3-api1-20210207
      Build:Feb�ESP-ROM:esp32c3-api1-20210207
      Build:Feb�ESP-ROM:esp32c3-api1-20210207
      Build:Feb�ESP-ROM:esp32c3-api1-20210207

i dont get any incremented value each boot.

**Comment by peturdainn** [comment]
Did you change the code to make it boot on either the timer or the GPIO? Because the sample code will always go back to deep sleep, there's a comment where you can return from the stub, and then after booting you can inspect the counter.

Another note is that this was written with IDF 4.4.x and might need small changes for IDF 5.x
(currently doing a new project with newer IDF so I should check if it needs changes)

**Comment by ZakiyaMiller** [comment]
Okay okay my bad , I think I got it , i misunderstood your code , your code doesn't print the incremented value unless you boot into the firmware using return, right ?
Another thing , is it possible to use printf in wakeup stub ?

**Comment by peturdainn** [comment]
not sure where your reply went, but to print from the stub you need to include (I think)

#include "rom/ets_sys.h"

and use ets_printf() to print, but beware that the string needs RTC_RODATA_ATTR and you will need to loop a bit to create a delay to get the string out before the deep sleep kicks in again (I did 100000 loops IIRC), and in that loop you need

REG_WRITE(TIMG_WDTFEED_REG(0), 1); 

or the watchdog boots you :)

**Comment by noobplayer48** [comment]
sorry for the inconvenience, i forgot to change the account and replied with a different one and later deleted it.
okay , thank you for the help . 
I want to ask a different question :
why does this code https://gist.github.com/igrr/54f7fbe0513ac14e1aea3fd7fbecfeab gives this error :
/Users/so20466256/espc3/main/main.cpp:34:10: fatal error: soc/rtc_io_reg.h: No such file or directory
 #include "soc/rtc_io_reg.h"
          ^~~~~~~~~~~~~~~~~~
compilation terminated.

this works perfectly fine in esp32 but in esp32c3 i m facing the error mentioned above. 
Yes, i did try adding  set_rtc_memory_crc(); below  REG_WRITE(RTC_ENTRY_ADDR_REG, (uint32_t)&wake_stub); but i dont think it has anything to do with that.
thanks in advance

**Comment by peturdainn** [comment]
Check the IDF doc for the target you use and IDF version, they change how things are done, including header files, between targets and IDF versions.

Espressif is not so fun in this aspect, porting and upgrading has many breaking changes :(

**Comment by noobplayer48** [comment]
idf example doesnt work either , bcz "#include "esp_wake_stub.h"" this file doesnt exist ,i think i thats bcz i m using esp idf 4.4 , i think i will use your example , thanks for the help.

**Comment by noobplayer48** [comment]
okay , one last ques, if u r using esp idf 4.4 , can u check if this example is getting compile on your machine:
https://github.com/espressif/esp-idf/tree/a7fbf452fa181452f266b16c49063e2ff069f119/examples/system/deep_sleep_wake_stub/main

**Comment by noobplayer48** [comment]
hey , sorry to disturb again , but do u know how to use adc in stub ? 
I tried implementing it simply using "analogRead()" while defining LDR value using RTC_DATA_ATTR, but get this error in the terminal :
    Guru Meditation Error: Core 0 panic'ed (Illegal instruction)
    Core 0 register dump:
    PC      : 0x420057ae  RA      : 0x500000da  SP      : 0x3fcde6f0  GP      : 0x00000000
    0x420057ae: __analogRead at /Users/so20466256/Embedded_Projects/project- 
     name/components/arduino/cores/esp32/esp32-hal-adc.c:153


later , tried using this way "  LDR_Val = SENS.sar_meas_start1.meas1_data_sar;
  SENS.sar_meas_wait2.force_xpd_sar = SENS_FORCE_XPD_SAR_PD; "
  

but SENS is not declared , probably bcz its not for espc3

**Comment by peturdainn** [comment]
heh, I'm not the Espressif helpline ;)

Code to be used in the stub has to run from RTC ram (which keeps power), that RAM is limited and if ADC needs lots of helpers those also need to be in RTC ram. So your best shot is to use direct register read/write and not IDF functions.
Also most powerdomains are switched off during deepsleep so you need to call esp_sleep_pd_config() to make sure ADC isn't powered down
